services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest # <- update image version here, see: https://github.com/AdguardTeam/AdGuardHome
    hostname: adguard.local
    depends_on:
      - unbound
    restart: always
    deploy:
      resources: # <- these settings are optional, but can help to limit resource reservations
        limits:
          memory: 768M
        reservations:
          memory: 256M
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Dashboard
      - "3000:3000/tcp" # first setup
      - "8080:80/tcp" # web ui -> http://localhost:8080/admin
# RECOMMENDED: Uncomment and adapt if you want to persist pihole configurations after restart
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    networks:
      dnsvlan:
        ipv4_address: 192.168.1.225 # <-- use this ip as dns when connected to pihole_dns_network (i.e. within a docker network)
  
  unbound:
    build: ./unbound
    container_name: unbound
    hostname: unbound.local
    restart: unless-stopped
    ports:
      - "5335:53/tcp" # expose a different port (5335) so you can use it directly
      - "5335:53/udp"
    networks:
      dnsvlan:
        ipv4_address: 192.168.1.226 # <-- this is used by pihole as upstream DNS

networks:
  # Define a custom subnet for pihole so that unbound can be an upstream DNS on port 53
  dnsvlan:
    name: dnsvlan
    driver: macvlan
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.224/30 # 172.21.200.1 - 172.21.200.254
